services:
  my-nicegui-app:
    build: .
    container_name: nicegui_app
    ports:
      - "8081:8080" # Maps server port 8081 to container port 8080
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage # Optional: Persist data if your app saves files